version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

  node:
    build: .
    container_name: node-container
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    networks:
      - mynetwork

volumes:
  mongo_data:

networks:
  mynetwork:
